### ISSUE TITLE
Checklist of all the tasks for milestone 3

### ISSUE THREAD

**Issue by akanshaVashisth** [UBC-MDS/filterizeR#13]
- [x] Write functions
- [x] Write tests
- [x] Use the following commands to complete the package:
     1.  load_all()
     2. check()
     3. document()
     4. test()
- [x] Check Branch coverage
- [x] Document the results of  branch coverage 
- [x] Update README:
     1. Description of how to install the package and use the functions
     2. An example with a toy dataset, if possible
     3. Screenshot of the output when we run your tests
- [x] Vignette
