### ISSUE TITLE
Milestone - 4 tasks

### ISSUE THREAD

**Issue by akanshaVashisth** [UBC-MDS/filterizeR#20]
- [x] Add appropriate exception handler for all functions.

- [x] Add adequate integration tests in each package, if applicable.

- [x] Set up continuous integration testing using Travis and add a passing build stamp for each package README files.

- [x] In your README, include a clear description of how to install your package and call your functions. Also, include an example with a toy dataset and a screenshot of the output when you run tests.

- [x] Individually report the contributions of each team member by filling out this standard form by Sunday, March 10th at noon.
